import type { Language } from '../i18n';

const LOCALIZED_CAPITALS: Record<string, Partial<Record<Language, string>>> = {
  EU: { ru: 'Брюссель', de: 'Brüssel', es: 'Bruselas', pt: 'Bruxelas', fr: 'Bruxelles' },
  AT: { ru: 'Вена', de: 'Wien', es: 'Viena', pt: 'Viena', fr: 'Vienne' },
  BE: { ru: 'Брюссель', de: 'Brüssel', es: 'Bruselas', pt: 'Bruxelas', fr: 'Bruxelles' },
  BG: { ru: 'София' },
  HR: { ru: 'Загреб' },
  CY: { ru: 'Никосия', de: 'Nikosia', pt: 'Nicósia', fr: 'Nicosie' },
  CZ: { ru: 'Прага', de: 'Prag', es: 'Praga', pt: 'Praga' },
  DK: { ru: 'Копенгаген', de: 'Kopenhagen', es: 'Copenhague', pt: 'Copenhaga', fr: 'Copenhague' },
  EE: { ru: 'Таллин' },
  FI: { ru: 'Хельсинки' },
  FR: { ru: 'Париж' },
  DE: { ru: 'Берлин' },
  EL: { ru: 'Афины', de: 'Athen', es: 'Atenas', pt: 'Atenas', fr: 'Athènes' },
  HU: { ru: 'Будапешт' },
  IE: { ru: 'Дублин', es: 'Dublín' },
  IT: { ru: 'Рим', de: 'Rom', es: 'Roma', pt: 'Roma' },
  LV: { ru: 'Рига' },
  LT: { ru: 'Вильнюс' },
  LU: { ru: 'Люксембург', es: 'Luxemburgo', pt: 'Luxemburgo' },
  MT: { ru: 'Валлетта' },
  NL: { ru: 'Амстердам' },
  PL: { ru: 'Варшава', de: 'Warschau', es: 'Varsovia', pt: 'Varsóvia', fr: 'Varsovie' },
  PT: { ru: 'Лиссабон', de: 'Lissabon', es: 'Lisboa', pt: 'Lisboa', fr: 'Lisbonne' },
  RO: { ru: 'Бухарест', de: 'Bukarest', es: 'Bucarest', pt: 'Bucareste', fr: 'Bucarest' },
  SK: { ru: 'Братислава' },
  SI: { ru: 'Любляна', es: 'Liubliana', pt: 'Liubliana' },
  ES: { ru: 'Мадрид' },
  SE: { ru: 'Стокгольм', es: 'Estocolmo', pt: 'Estocolmo' },
  IS: { ru: 'Рейкьявик', es: 'Reikiavik', pt: 'Reiquiavique' },
  LI: { ru: 'Вадуц' },
  NO: { ru: 'Осло' },
  CH: { ru: 'Берн', es: 'Berna', pt: 'Berna', fr: 'Berne' },
  AL: { ru: 'Тирана' },
  BA: { ru: 'Сараево' },
  ME: { ru: 'Подгорица' },
  MK: { ru: 'Скопье' },
  MD: { ru: 'Кишинёв', de: 'Chișinău', es: 'Chisináu', pt: 'Chisinau', fr: 'Chișinău' },
  RS: { ru: 'Белград', de: 'Belgrad', es: 'Belgrado', pt: 'Belgrado' },
  TR: { ru: 'Анкара' },
  GE: { ru: 'Тбилиси' },
  UA: { ru: 'Киев' },
  XK: { ru: 'Приштина' },
  US: { ru: 'Вашингтон' },
  CA: { ru: 'Оттава' },
  MX: { ru: 'Мехико' },
  UK: { ru: 'Лондон' },
  JP: { ru: 'Токио', de: 'Tokio', es: 'Tokio', pt: 'Tóquio' },
  AU: { ru: 'Канберра' },
  AM: { ru: 'Ереван' },
  AZ: { ru: 'Баку' },
  BY: { ru: 'Минск' },
  KZ: { ru: 'Астана' },
  KG: { ru: 'Бишкек' },
  RU: { ru: 'Москва' },
  TJ: { ru: 'Душанбе' },
  TM: { ru: 'Ашхабад' },
  UZ: { ru: 'Ташкент' },
  IL: { ru: 'Иерусалим' },
  AE: { ru: 'Абу-Даби' },
  SA: { ru: 'Эр-Рияд' },
  OM: { ru: 'Маскат' },
  QA: { ru: 'Доха' },
  KR: { ru: 'Сеул' },
  MN: { ru: 'Улан-Батор' },
  ID: { ru: 'Джакарта' },
  TH: { ru: 'Бангкок' },
  VN: { ru: 'Ханой' },
  MY: { ru: 'Куала-Лумпур' },
  SG: { ru: 'Сингапур' },
  PH: { ru: 'Манила' },
  CN: { ru: 'Пекин' },
  IN: { ru: 'Нью-Дели' },
  PK: { ru: 'Исламабад' },
  BD: { ru: 'Дакка' },
  EG: { ru: 'Каир' },
  ZA: { ru: 'Претория' },
  NG: { ru: 'Абуджа' },
  KE: { ru: 'Найроби' },
  ET: { ru: 'Аддис-Абеба' },
  ZM: { ru: 'Лусака' },
  NE: { ru: 'Ниамей' },
  TD: { ru: 'Нджамена' },
  CI: { ru: 'Ямусукро' },
  CD: { ru: 'Киншаса' },
  SN: { ru: 'Дакар' },
  NA: { ru: 'Виндхук' },
  AO: { ru: 'Луанда' },
  MA: { ru: 'Рабат' },
  DZ: { ru: 'Алжир' },
  TN: { ru: 'Тунис' },
  GH: { ru: 'Аккра' },
  BW: { ru: 'Габороне' },
  BR: { ru: 'Бразилиа' },
  AR: { ru: 'Буэнос-Айрес' },
  BO: { ru: 'Сукре' },
  CL: { ru: 'Сантьяго' },
  CO: { ru: 'Богота' },
  EC: { ru: 'Кито' },
  PE: { ru: 'Лима' },
  PY: { ru: 'Асунсьон' },
  UY: { ru: 'Монтевидео' },
  VE: { ru: 'Каракас' },
  GY: { ru: 'Джорджтаун' },
  SR: { ru: 'Парамарибо' },
};

export function getLocalizedCapitalName(
  countryCode: string,
  locale: Language,
  fallbackName: string,
): string {
  return LOCALIZED_CAPITALS[countryCode]?.[locale] ?? fallbackName;
}
