export interface CountryMeta {
  code: string;
  name: string;
  region: 'EU' | 'EFTA' | 'Candidate' | 'NorthAmerica' | 'Other';
  flag: string;
}

export const COUNTRIES: CountryMeta[] = [
  // EU-27
  { code: 'AT', name: 'Austria', region: 'EU', flag: '\u{1F1E6}\u{1F1F9}' },
  { code: 'BE', name: 'Belgium', region: 'EU', flag: '\u{1F1E7}\u{1F1EA}' },
  { code: 'BG', name: 'Bulgaria', region: 'EU', flag: '\u{1F1E7}\u{1F1EC}' },
  { code: 'HR', name: 'Croatia', region: 'EU', flag: '\u{1F1ED}\u{1F1F7}' },
  { code: 'CY', name: 'Cyprus', region: 'EU', flag: '\u{1F1E8}\u{1F1FE}' },
  { code: 'CZ', name: 'Czechia', region: 'EU', flag: '\u{1F1E8}\u{1F1FF}' },
  { code: 'DK', name: 'Denmark', region: 'EU', flag: '\u{1F1E9}\u{1F1F0}' },
  { code: 'EE', name: 'Estonia', region: 'EU', flag: '\u{1F1EA}\u{1F1EA}' },
  { code: 'FI', name: 'Finland', region: 'EU', flag: '\u{1F1EB}\u{1F1EE}' },
  { code: 'FR', name: 'France', region: 'EU', flag: '\u{1F1EB}\u{1F1F7}' },
  { code: 'DE', name: 'Germany', region: 'EU', flag: '\u{1F1E9}\u{1F1EA}' },
  { code: 'EL', name: 'Greece', region: 'EU', flag: '\u{1F1EC}\u{1F1F7}' },
  { code: 'HU', name: 'Hungary', region: 'EU', flag: '\u{1F1ED}\u{1F1FA}' },
  { code: 'IE', name: 'Ireland', region: 'EU', flag: '\u{1F1EE}\u{1F1EA}' },
  { code: 'IT', name: 'Italy', region: 'EU', flag: '\u{1F1EE}\u{1F1F9}' },
  { code: 'LV', name: 'Latvia', region: 'EU', flag: '\u{1F1F1}\u{1F1FB}' },
  { code: 'LT', name: 'Lithuania', region: 'EU', flag: '\u{1F1F1}\u{1F1F9}' },
  { code: 'LU', name: 'Luxembourg', region: 'EU', flag: '\u{1F1F1}\u{1F1FA}' },
  { code: 'MT', name: 'Malta', region: 'EU', flag: '\u{1F1F2}\u{1F1F9}' },
  { code: 'NL', name: 'Netherlands', region: 'EU', flag: '\u{1F1F3}\u{1F1F1}' },
  { code: 'PL', name: 'Poland', region: 'EU', flag: '\u{1F1F5}\u{1F1F1}' },
  { code: 'PT', name: 'Portugal', region: 'EU', flag: '\u{1F1F5}\u{1F1F9}' },
  { code: 'RO', name: 'Romania', region: 'EU', flag: '\u{1F1F7}\u{1F1F4}' },
  { code: 'SK', name: 'Slovakia', region: 'EU', flag: '\u{1F1F8}\u{1F1F0}' },
  { code: 'SI', name: 'Slovenia', region: 'EU', flag: '\u{1F1F8}\u{1F1EE}' },
  { code: 'ES', name: 'Spain', region: 'EU', flag: '\u{1F1EA}\u{1F1F8}' },
  { code: 'SE', name: 'Sweden', region: 'EU', flag: '\u{1F1F8}\u{1F1EA}' },
  // EFTA
  { code: 'IS', name: 'Iceland', region: 'EFTA', flag: '\u{1F1EE}\u{1F1F8}' },
  { code: 'LI', name: 'Liechtenstein', region: 'EFTA', flag: '\u{1F1F1}\u{1F1EE}' },
  { code: 'NO', name: 'Norway', region: 'EFTA', flag: '\u{1F1F3}\u{1F1F4}' },
  { code: 'CH', name: 'Switzerland', region: 'EFTA', flag: '\u{1F1E8}\u{1F1ED}' },
  // Candidates
  { code: 'AL', name: 'Albania', region: 'Candidate', flag: '\u{1F1E6}\u{1F1F1}' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Candidate', flag: '\u{1F1E7}\u{1F1E6}' },
  { code: 'ME', name: 'Montenegro', region: 'Candidate', flag: '\u{1F1F2}\u{1F1EA}' },
  { code: 'MK', name: 'North Macedonia', region: 'Candidate', flag: '\u{1F1F2}\u{1F1F0}' },
  { code: 'MD', name: 'Moldova', region: 'Candidate', flag: '\u{1F1F2}\u{1F1E9}' },
  { code: 'RS', name: 'Serbia', region: 'Candidate', flag: '\u{1F1F7}\u{1F1F8}' },
  { code: 'TR', name: 'Turkey', region: 'Candidate', flag: '\u{1F1F9}\u{1F1F7}' },
  { code: 'GE', name: 'Georgia', region: 'Candidate', flag: '\u{1F1EC}\u{1F1EA}' },
  { code: 'UA', name: 'Ukraine', region: 'Candidate', flag: '\u{1F1FA}\u{1F1E6}' },
  { code: 'XK', name: 'Kosovo', region: 'Candidate', flag: '\u{1F1FD}\u{1F1F0}' },
  // North America
  { code: 'US', name: 'United States', region: 'NorthAmerica', flag: '\u{1F1FA}\u{1F1F8}' },
  { code: 'CA', name: 'Canada', region: 'NorthAmerica', flag: '\u{1F1E8}\u{1F1E6}' },
  { code: 'MX', name: 'Mexico', region: 'NorthAmerica', flag: '\u{1F1F2}\u{1F1FD}' },
  // Other
  { code: 'UK', name: 'United Kingdom', region: 'Other', flag: '\u{1F1EC}\u{1F1E7}' },
  { code: 'JP', name: 'Japan', region: 'Other', flag: '\u{1F1EF}\u{1F1F5}' },
  { code: 'AU', name: 'Australia', region: 'Other', flag: '\u{1F1E6}\u{1F1FA}' },
  { code: 'AM', name: 'Armenia', region: 'Other', flag: '\u{1F1E6}\u{1F1F2}' },
  { code: 'AZ', name: 'Azerbaijan', region: 'Other', flag: '\u{1F1E6}\u{1F1FF}' },
  { code: 'BY', name: 'Belarus', region: 'Other', flag: '\u{1F1E7}\u{1F1FE}' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Other', flag: '\u{1F1F0}\u{1F1FF}' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Other', flag: '\u{1F1F0}\u{1F1EC}' },
  { code: 'RU', name: 'Russia', region: 'Other', flag: '\u{1F1F7}\u{1F1FA}' },
  { code: 'TJ', name: 'Tajikistan', region: 'Other', flag: '\u{1F1F9}\u{1F1EF}' },
  { code: 'TM', name: 'Turkmenistan', region: 'Other', flag: '\u{1F1F9}\u{1F1F2}' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Other', flag: '\u{1F1FA}\u{1F1FF}' },
  { code: 'IL', name: 'Israel', region: 'Other', flag: '\u{1F1EE}\u{1F1F1}' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Other', flag: '\u{1F1E6}\u{1F1EA}' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Other', flag: '\u{1F1F8}\u{1F1E6}' },
  { code: 'OM', name: 'Oman', region: 'Other', flag: '\u{1F1F4}\u{1F1F2}' },
  { code: 'QA', name: 'Qatar', region: 'Other', flag: '\u{1F1F6}\u{1F1E6}' },
  { code: 'KR', name: 'South Korea', region: 'Other', flag: '\u{1F1F0}\u{1F1F7}' },
  { code: 'MN', name: 'Mongolia', region: 'Other', flag: '\u{1F1F2}\u{1F1F3}' },
  { code: 'ID', name: 'Indonesia', region: 'Other', flag: '\u{1F1EE}\u{1F1E9}' },
  { code: 'TH', name: 'Thailand', region: 'Other', flag: '\u{1F1F9}\u{1F1ED}' },
  { code: 'VN', name: 'Vietnam', region: 'Other', flag: '\u{1F1FB}\u{1F1F3}' },
  { code: 'MY', name: 'Malaysia', region: 'Other', flag: '\u{1F1F2}\u{1F1FE}' },
  { code: 'SG', name: 'Singapore', region: 'Other', flag: '\u{1F1F8}\u{1F1EC}' },
  { code: 'PH', name: 'Philippines', region: 'Other', flag: '\u{1F1F5}\u{1F1ED}' },
  { code: 'CN', name: 'China', region: 'Other', flag: '\u{1F1E8}\u{1F1F3}' },
  { code: 'IN', name: 'India', region: 'Other', flag: '\u{1F1EE}\u{1F1F3}' },
  { code: 'PK', name: 'Pakistan', region: 'Other', flag: '\u{1F1F5}\u{1F1F0}' },
  { code: 'BD', name: 'Bangladesh', region: 'Other', flag: '\u{1F1E7}\u{1F1E9}' },
  { code: 'EG', name: 'Egypt', region: 'Other', flag: '\u{1F1EA}\u{1F1EC}' },
  { code: 'ZA', name: 'South Africa', region: 'Other', flag: '\u{1F1FF}\u{1F1E6}' },
  { code: 'NG', name: 'Nigeria', region: 'Other', flag: '\u{1F1F3}\u{1F1EC}' },
  { code: 'KE', name: 'Kenya', region: 'Other', flag: '\u{1F1F0}\u{1F1EA}' },
  { code: 'ET', name: 'Ethiopia', region: 'Other', flag: '\u{1F1EA}\u{1F1F9}' },
  { code: 'ZM', name: 'Zambia', region: 'Other', flag: '\u{1F1FF}\u{1F1F2}' },
  { code: 'NE', name: 'Niger', region: 'Other', flag: '\u{1F1F3}\u{1F1EA}' },
  { code: 'TD', name: 'Chad', region: 'Other', flag: '\u{1F1F9}\u{1F1E9}' },
  { code: 'CI', name: "Cote d'Ivoire", region: 'Other', flag: '\u{1F1E8}\u{1F1EE}' },
  { code: 'CD', name: 'Democratic Republic of the Congo', region: 'Other', flag: '\u{1F1E8}\u{1F1E9}' },
  { code: 'SN', name: 'Senegal', region: 'Other', flag: '\u{1F1F8}\u{1F1F3}' },
  { code: 'NA', name: 'Namibia', region: 'Other', flag: '\u{1F1F3}\u{1F1E6}' },
  { code: 'AO', name: 'Angola', region: 'Other', flag: '\u{1F1E6}\u{1F1F4}' },
  { code: 'MA', name: 'Morocco', region: 'Other', flag: '\u{1F1F2}\u{1F1E6}' },
  { code: 'DZ', name: 'Algeria', region: 'Other', flag: '\u{1F1E9}\u{1F1FF}' },
  { code: 'TN', name: 'Tunisia', region: 'Other', flag: '\u{1F1F9}\u{1F1F3}' },
  { code: 'GH', name: 'Ghana', region: 'Other', flag: '\u{1F1EC}\u{1F1ED}' },
  { code: 'BW', name: 'Botswana', region: 'Other', flag: '\u{1F1E7}\u{1F1FC}' },
  { code: 'BR', name: 'Brazil', region: 'Other', flag: '\u{1F1E7}\u{1F1F7}' },
  { code: 'AR', name: 'Argentina', region: 'Other', flag: '\u{1F1E6}\u{1F1F7}' },
  { code: 'BO', name: 'Bolivia', region: 'Other', flag: '\u{1F1E7}\u{1F1F4}' },
  { code: 'CL', name: 'Chile', region: 'Other', flag: '\u{1F1E8}\u{1F1F1}' },
  { code: 'CO', name: 'Colombia', region: 'Other', flag: '\u{1F1E8}\u{1F1F4}' },
  { code: 'EC', name: 'Ecuador', region: 'Other', flag: '\u{1F1EA}\u{1F1E8}' },
  { code: 'PE', name: 'Peru', region: 'Other', flag: '\u{1F1F5}\u{1F1EA}' },
  { code: 'PY', name: 'Paraguay', region: 'Other', flag: '\u{1F1F5}\u{1F1FE}' },
  { code: 'UY', name: 'Uruguay', region: 'Other', flag: '\u{1F1FA}\u{1F1FE}' },
  { code: 'VE', name: 'Venezuela', region: 'Other', flag: '\u{1F1FB}\u{1F1EA}' },
  { code: 'GY', name: 'Guyana', region: 'Other', flag: '\u{1F1EC}\u{1F1FE}' },
  { code: 'SR', name: 'Suriname', region: 'Other', flag: '\u{1F1F8}\u{1F1F7}' },
];
